Task completed
NikolayFatkullin/jv-create-annotation pull request #1
Opened 2021-01-03 21:41 UTC by NikolayFatkullin

- Created classes: Bet, BetDaoImpl, ConsoleHandler, Main, Player, PlayerDaoImpl, Storage;

- Created interfaces: PlayerDao, BetDao;

2021-01-06 10:33 UTC, ivlytvynets approved these changes

2021-01-08 11:40 UTC, dmytro-hryhoruk requested changes

2021-01-08 11:40 UTC, dmytro-hryhoruk commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +    BetDao betDao = new BetDaoImpl();
access modifiers

2021-01-08 11:40 UTC, dmytro-hryhoruk commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +    BetDao betDao = new BetDaoImpl();
What about other Dao?

2021-01-08 11:40 UTC, dmytro-hryhoruk commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +            betDao.add(bet);
let's add only if bet != nul and user getAll() to print all of them at the end

2021-01-08 14:40 UTC, dmytro-hryhoruk approved these changes

2021-01-08 14:40 UTC, dmytro-hryhoruk commented on src/main/java/core/basesyntax/controller/ConsoleHandler.java
> +            System.out.println(bet == null ? null : bet.toString());
This check and calling toString() done automatically  by System.out.println(check it)

2021-01-08 15:46 UTC, merged