Second HomeWork completed
NikolayFatkullin/jv-create-annotation pull request #2
Opened 2021-01-10 02:49 UTC by NikolayFatkullin

- Created annotation @Dao, @Inject;
- Created classes Factory, Injector, AnnotationException;

2021-01-10 18:35 UTC, boroda4436 commented
I haven't reviewed your code. Just launched. This is not a rejection reason, just advice. Your app will be better if the user will not see exceptions like `IndexOutOfBounds` or `NullPointerException`.
![image](https://user-images.githubusercontent.com/13794896/104132013-3c27e200-5383-11eb-9c16-5144fe410826.png)

2021-01-10 18:55 UTC, Fedich09 approved these changes
good joberino))

2021-01-11 08:58 UTC, RomanDubovskyi requested changes
good job, left one minor comment, rest is good

2021-01-11 08:58 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/lib/Injector.java
> +            if (field.getAnnotation(Inject.class) != null) {
FYI you use here isAnnotationPresent as well (it's optional)

2021-01-11 08:58 UTC, RomanDubovskyi commented on src/main/java/core/basesyntax/lib/Injector.java
> +                    throw new AnnotationException("This type of class doesn't have "
add type to message to make more informative

2021-01-11 12:24 UTC, RomanDubovskyi approved these changes

2021-01-11 15:40 UTC, merged